"""Build explicit C lab contracts, grader drivers and reference verification fixtures.
Reference implementations are kept under tools/, never loaded by the game UI.
"""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
qs=json.loads((ROOT/'js/data/side-quests.js').read_text(encoding='utf-8').split('window.SIDE_QUESTS =',1)[1].strip().rstrip(';'))
D={}
INC='#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <limits.h>\n#include <stdint.h>\n#include <ctype.h>\n'
def case(inp='',files=None):return {'input':inp,'files':files or {}}
def main(n,contract,ref,inputs):D[n]=dict(contract=contract,reference=INC+ref,starter='#include <stdio.h>\n\nint main(void)\n{\n    /* Write your implementation here. */\n    return 0;\n}\n',harness='',cases=[case(x) if isinstance(x,str) else x for x in inputs])
def lib(n,contract,types,prototypes,ref,driver,inputs,tracked=False):D[n]=dict(contract=contract,reference=INC+types+'\n'+ref,starter=INC+types+'\n'+prototypes+'\n/* Implement the functions above. The game supplies main(). */\n',harness=INC+(TRACK if tracked else '')+'\n#include "quest.c"\n'+(UNTRACK if tracked else '')+driver,cases=[case(x) if isinstance(x,str) else x for x in inputs])
TRACK=r'''
static void *allocations[256];
static int fail_next=0;
static int live_blocks(void){int n=0;for(int i=0;i<256;i++)n+=allocations[i]!=NULL;return n;}
static void remember(void *p){if(!p)return;for(int i=0;i<256;i++)if(!allocations[i]){allocations[i]=p;return;}abort();}
static void forget(void *p){if(!p)return;for(int i=0;i<256;i++)if(allocations[i]==p){allocations[i]=NULL;return;}abort();}
static void *q_malloc(size_t n){if(fail_next){fail_next=0;return NULL;}void *p=malloc(n);remember(p);return p;}
static void *q_calloc(size_t n,size_t s){if(fail_next){fail_next=0;return NULL;}void *p=calloc(n,s);remember(p);return p;}
static void *q_realloc(void *p,size_t n){if(fail_next){fail_next=0;return NULL;}void *old=p;void *next=realloc(p,n);if(next||!n){forget(old);remember(next);}return next;}
static void q_free(void *p){forget(p);free(p);}
#define malloc q_malloc
#define calloc q_calloc
#define realloc q_realloc
#define free q_free
'''
# The harness uses all four wrappers so -Wunused-function does not penalize a learner's allocator choice.
UNTRACK='\n#undef malloc\n#undef calloc\n#undef realloc\n#undef free\nstatic void track_ready(void){(void)q_malloc;(void)q_calloc;(void)q_realloc;(void)q_free;}\n'
main(1,'No input. Declare and initialize the trainer ID (42), party count (3), and fee in cents (125). Print exactly the three labeled lines in the sample, each ending in a newline.',r'''int main(void){int trainer=42,party=3,fee=125;printf("Trainer ID: %d\nParty count: %d\nFee (cents): %d\n",trainer,party,fee);return 0;}''',[''])
main(2,'Input: two integer quantities, balls then potions, each 0-99. Prices are 200 and 300 cents. Print Total: $D.CC followed by a newline. Invalid quantities print ERROR and a newline. Do not print input prompts.',r'''int main(void){int a,b;if(scanf("%d%d",&a,&b)!=2||a<0||a>99||b<0||b>99){puts("ERROR");return 0;}int c=200*a+300*b;printf("Total: $%d.%02d\n",c/100,c%100);return 0;}''',['2 3\n','0 0\n','99 99\n','1 0\n','0 1\n','-1 3\n','100 0\n','7 13\n'])
main(3,'Input: current HP, maximum HP, potion flag (0 or 1). Maximum is 1-999, current is 0 through maximum. Invalid input prints ERROR. Otherwise print RETREAT at zero HP, HEAL at or below 25% with a potion, or ATTACK. Print one newline.',r'''int main(void){int h,m,p;if(scanf("%d%d%d",&h,&m,&p)!=3||m<1||m>999||h<0||h>m||p<0||p>1)puts("ERROR");else if(!h)puts("RETREAT");else if(h*4<=m&&p)puts("HEAL");else puts("ATTACK");return 0;}''',['25 100 1','26 100 1','25 100 0','0 100 1','1 3 1','1 4 1','10 0 1','101 100 0','249 999 1'])
main(4,'Read exactly seven integers, each 0-10000. Use a loop without an array to print total, average to two decimals, and earliest best day (1-based), on one line separated by single spaces. Invalid value or missing input prints ERROR. End with a newline.',r'''int main(void){int sum=0,best=-1,day=1;for(int i=1;i<=7;i++){int n;if(scanf("%d",&n)!=1||n<0||n>10000){puts("ERROR");return 0;}sum+=n;if(n>best){best=n;day=i;}}printf("%d %.2f %d\n",sum,sum/7.0,day);return 0;}''',['1 2 3 4 5 6 7','0 0 0 0 0 0 0','9 1 9 2 3 4 5','10000 10000 10000 10000 10000 10000 10000','1 2 -1 4 5 6 7','1 2 3'])
lib(5,'Implement int heal_hp(int current,int maximum,int amount) and int estimate_damage(int power,int attack,int defense). Valid HP: maximum 1-999, current 0..maximum, amount 0..999. Healing clamps at maximum. Damage arguments are 1-100 and result is power*attack/defense with integer division. Invalid arguments return -1. Driver input H c m a or D p a d; prints the returned integer.', '', 'int heal_hp(int current,int maximum,int amount);\nint estimate_damage(int power,int attack,int defense);',r'''int heal_hp(int c,int m,int a){if(m<1||m>999||c<0||c>m||a<0||a>999)return -1;return a>m-c?m:c+a;}int estimate_damage(int p,int a,int d){if(p<1||p>100||a<1||a>100||d<1||d>100)return -1;return p*a/d;}''',r'''int main(void){char c;int a,b,d;if(scanf(" %c%d%d%d",&c,&a,&b,&d)!=4)return 1;printf("%d\n",c=='H'?heal_hp(a,b,d):estimate_damage(a,b,d));return 0;}''',['H 35 39 10','H 20 39 10','H 0 1 999','H 40 39 0','D 10 20 8','D 1 1 100','D 10 20 0','D 100 100 1'])
main(6,'Input: party size 1-6 followed by that many levels 1-100. Store levels in a six-element array. Print min max average on one line, average with two decimals. Invalid size, level or missing value prints ERROR. End with a newline.',r'''int main(void){int n,a[6];if(scanf("%d",&n)!=1||n<1||n>6){puts("ERROR");return 0;}for(int i=0;i<n;i++)if(scanf("%d",a+i)!=1||a[i]<1||a[i]>100){puts("ERROR");return 0;}int lo=a[0],hi=a[0],sum=0;for(int i=0;i<n;i++){if(a[i]<lo)lo=a[i];if(a[i]>hi)hi=a[i];sum+=a[i];}printf("%d %d %.2f\n",lo,hi,sum/(double)n);return 0;}''',['3 5 10 15','1 5','6 100 1 20 30 40 50','0','7 1 2 3 4 5 6 7','2 0 5'])
lib(7,'Use Registry from the starter. Implement registry_add: name must contain 1-20 ASCII letters/spaces and at least one letter. Return 1 if added, 0 for a case-insensitive duplicate, -1 for invalid input or full capacity (6). Preserve original spelling. Duplicate detection takes priority over full capacity. Driver: count then one nickname per line; prints result and current count after each addition, then all stored names. Registry begins empty.', 'typedef struct {char names[6][21]; int count;} Registry;', 'int registry_add(Registry *r,const char *name);',r'''int registry_add(Registry *r,const char *s){size_t n=strlen(s);int letter=0;if(!n||n>20)return -1;for(size_t i=0;i<n;i++){unsigned char c=(unsigned char)s[i];if((c>='A'&&c<='Z')||(c>='a'&&c<='z'))letter=1;else if(c!=' ')return -1;}if(!letter)return -1;for(int i=0;i<r->count;i++){size_t j=0;while(s[j]&&r->names[i][j]&&tolower((unsigned char)s[j])==tolower((unsigned char)r->names[i][j]))j++;if(!s[j]&&!r->names[i][j])return 0;}if(r->count==6)return -1;strcpy(r->names[r->count++],s);return 1;}''',r'''int main(void){Registry r;memset(&r,0,sizeof r);int n;if(scanf("%d",&n)!=1)return 1;getchar();for(int i=0;i<n;i++){char s[256];if(!fgets(s,sizeof s,stdin))s[0]=0;s[strcspn(s,"\r\n")]=0;int v=registry_add(&r,s);printf("%d %d\n",v,r.count);}for(int i=0;i<r.count;i++)puts(r.names[i]);return 0;}''',['3\nPikachu\npikachu\nMr Mime\n','4\n\n123\n   \nEevee\n','8\nA\nB\nC\nD\nE\nF\nG\na\n','2\nABCDEFGHIJKLMNOPQRST\nABCDEFGHIJKLMNOPQRSTU\n'])
OBS='typedef enum {FOREST,WATER,CAVE} Habitat;\ntypedef struct {char species[21];int level;Habitat habitat;} Observation;'
lib(8,'Implement filter_observations with the supplied Observation type. Copy records matching habitat and level >= minimum into out, preserving order; return the number copied. n is 0-10 and input records are valid. Driver: n habitat(0=forest,1=water,2=cave) minimum, then n lines species level habitat. Output is count, then matching records (one per line).',OBS,'size_t filter_observations(const Observation *items,size_t n,Habitat habitat,int minimum,Observation *out);',r'''size_t filter_observations(const Observation *v,size_t n,Habitat h,int m,Observation *out){size_t k=0;for(size_t i=0;i<n;i++)if(v[i].habitat==h&&v[i].level>=m)out[k++]=v[i];return k;}''',r'''int main(void){Observation a[10],out[10];int n,h,m;if(scanf("%d%d%d",&n,&h,&m)!=3||n<0||n>10)return 1;for(int i=0;i<n;i++){int x;if(scanf("%20s%d%d",a[i].species,&a[i].level,&x)!=3)return 1;a[i].habitat=(Habitat)x;}size_t k=filter_observations(a,(size_t)n,(Habitat)h,m,out);if(k>10)return 1;printf("%zu\n",k);for(size_t i=0;i<k;i++)printf("%s %d %d\n",out[i].species,out[i].level,out[i].habitat);return 0;}''',['2 0 10\nPikachu 12 0\nZubat 8 2','0 2 1','3 1 20\nSquirtle 20 1\nLapras 30 1\nPikachu 50 0','1 0 100\nPikachu 99 0'])
lib(9,'Implement roster_init, roster_append and roster_destroy. init allocates capacity 2 and returns 1, or resets all fields and returns 0 on failure. Append valid levels (1-100), doubling capacity only when full; return 0 without changes on invalid level, allocation failure, or size overflow. Destroy frees memory and zeros all fields. Driver input: command count, then A level, F (fail next allocation), or X (destroy). It prints append result, size, capacity and values after A, then cleanup and outstanding-allocation count. A failed append must preserve earlier values.', 'typedef struct {int *data;size_t size,capacity;} Roster;', 'int roster_init(Roster *r);\nint roster_append(Roster *r,int level);\nvoid roster_destroy(Roster *r);',r'''int roster_init(Roster *r){r->size=0;r->capacity=0;r->data=malloc(2*sizeof(int));if(!r->data)return 0;r->capacity=2;return 1;}int roster_append(Roster *r,int v){if(v<1||v>100)return 0;if(r->size==r->capacity){size_t c=r->capacity?r->capacity:1;if(c>SIZE_MAX/2||c*2>SIZE_MAX/sizeof(int))return 0;c*=2;int *p=realloc(r->data,c*sizeof(int));if(!p)return 0;r->data=p;r->capacity=c;}r->data[r->size++]=v;return 1;}void roster_destroy(Roster *r){free(r->data);r->data=NULL;r->size=r->capacity=0;}''',r'''int main(void){track_ready();Roster r={0};printf("INIT %d\n",roster_init(&r));int n;if(scanf("%d",&n)!=1)return 1;for(int i=0;i<n;i++){char c;int v;if(scanf(" %c",&c)!=1)return 1;if(c=='F')fail_next=1;else if(c=='X')roster_destroy(&r);else if(c=='O'){size_t os=r.size,oc=r.capacity;r.size=r.capacity=SIZE_MAX/2+1;printf("OVERFLOW %d\n",roster_append(&r,5));r.size=os;r.capacity=oc;}else{if(scanf("%d",&v)!=1)return 1;int ok=roster_append(&r,v);printf("%d %zu %zu",ok,r.size,r.capacity);if(r.size>100)return 1;for(size_t j=0;j<r.size;j++)printf(" %d",r.data[j]);puts("");}}roster_destroy(&r);printf("CLEAN %zu %zu %d\n",r.size,r.capacity,r.data==NULL);printf("LIVE %d\n",live_blocks());return 0;}''',['5 A 5 A 10 A 15 A 20 A 25','5 A 5 A 10 F A 15 A 20','4 A 0 A 101 X A 7','1 O'],True)
main(13,'Input: meters (0-100000) and speed in km/h (0.1-20), both double. Print kilometers and minutes with two decimal places, separated by one space and ending with newline. Invalid input prints ERROR.',r'''int main(void){double m,s;if(scanf("%lf%lf",&m,&s)!=2||m<0||m>100000||s<0.1||s>20){puts("ERROR");return 0;}printf("%.2f %.2f\n",m/1000,m/1000/s*60);return 0;}''',['1500 3','0 1','100000 20','2500 5','10 0','-1 1'])
main(14,'Input: bottle count 0-10000 and crate capacity 1-100. Print full crates and leftovers separated by one space and followed by newline. Invalid input prints ERROR.',r'''int main(void){int n,c;if(scanf("%d%d",&n,&c)!=2||n<0||n>10000||c<1||c>100)puts("ERROR");else printf("%d %d\n",n/c,n%c);return 0;}''',['10 3','12 4','0 5','10000 99','3 0','-1 5'])
main(15,'Read one integer level. Print BASIC for 1-15, STANDARD for 16-35, ADVANCED for 36-100, otherwise ERROR. End with newline.',r'''int main(void){int n;if(scanf("%d",&n)!=1||n<1||n>100)puts("ERROR");else puts(n<=15?"BASIC":n<=35?"STANDARD":"ADVANCED");return 0;}''',[str(n) for n in [0,1,15,16,35,36,100,101]])
main(16,'Read integer sessions 1-10. Row i contains exactly i asterisks, followed by newline. Invalid sessions print ERROR. Use nested loops, with no spaces in the chart.',r'''int main(void){int n;if(scanf("%d",&n)!=1||n<1||n>10){puts("ERROR");return 0;}for(int i=1;i<=n;i++){for(int j=0;j<i;j++)putchar('*');putchar('\n');}return 0;}''',['1','3','10','0','11'])
main(17,'Read count 0-100 then count species codes 1-6. Print six counts in code order, separated by single spaces, no trailing space, and newline. Any invalid count/code or missing input prints only ERROR.',r'''int main(void){int n,a[6]={0};if(scanf("%d",&n)!=1||n<0||n>100){puts("ERROR");return 0;}for(int i=0;i<n;i++){int v;if(scanf("%d",&v)!=1||v<1||v>6){puts("ERROR");return 0;}a[v-1]++;}for(int i=0;i<6;i++)printf("%s%d",i?" ":"",a[i]);puts("");return 0;}''',['3 1 1 6','0','6 6 5 4 3 2 1','2 0 1','2 1 7','100 '+' '.join(['2']*100)])
main(18,'Read count 0-20, count levels 1-100, then a search level 1-100. Use insertion sort ascending and linear search for the first match. Print sorted levels separated by spaces on line 1 (empty if count 0), then the 0-based first index or -1 on line 2. Invalid input prints ERROR.',r'''int main(void){int n,a[20],v;if(scanf("%d",&n)!=1||n<0||n>20){puts("ERROR");return 0;}for(int i=0;i<n;i++)if(scanf("%d",a+i)!=1||a[i]<1||a[i]>100){puts("ERROR");return 0;}if(scanf("%d",&v)!=1||v<1||v>100){puts("ERROR");return 0;}for(int i=1;i<n;i++){int x=a[i],j=i;while(j>0&&a[j-1]>x){a[j]=a[j-1];j--;}a[j]=x;}int found=-1;for(int i=0;i<n;i++){printf("%s%d",i?" ":"",a[i]);if(found<0&&a[i]==v)found=i;}printf("\n%d\n",found);return 0;}''',['3 3 1 3 3','0 5','5 5 4 3 2 1 8','1 100 100','2 0 5 5'])
main(19,'Read twelve yields (0-1000) in row-major order for a 3x4 garden. Print three row totals on line 1 and the best plot row and column (0-based) on line 2. Choose the earliest row-major plot on ties. Invalid input prints ERROR.',r'''int main(void){int a[3][4],tot[3]={0},br=0,bc=0,best=-1;for(int r=0;r<3;r++)for(int c=0;c<4;c++){if(scanf("%d",&a[r][c])!=1||a[r][c]<0||a[r][c]>1000){puts("ERROR");return 0;}tot[r]+=a[r][c];if(a[r][c]>best){best=a[r][c];br=r;bc=c;}}printf("%d %d %d\n%d %d\n",tot[0],tot[1],tot[2],br,bc);return 0;}''',['1 2 3 4 0 0 0 0 2 2 2 9',' '.join(['0']*12),'9 9 0 0 0 0 0 0 0 0 0 0','-1 '+' '.join(['0']*11)])
main(20,'Read supply lines until EOF. Each is item,quantity: item 1-20 ASCII letters, quantity 1-3 decimal digits with numeric value 0-999. No spaces, signs, quotes or extra comma. Strip CR/LF, accept final line without newline. Reject lines over 32 characters as one ERROR line. For each valid line print item then a space then numeric quantity and newline; invalid lines print ERROR.',r'''int main(void){char s[256];while(fgets(s,sizeof s,stdin)){size_t n=strlen(s);int longline=n&&!strchr(s,'\n')&&!feof(stdin);if(longline){int c;while((c=getchar())!='\n'&&c!=EOF){}puts("ERROR");continue;}s[strcspn(s,"\r\n")]=0;n=strlen(s);char *comma=strchr(s,',');int ok=n<=32&&comma&&comma>s&&(size_t)(comma-s)<=20;if(ok){for(char *x=s;x<comma;x++)if(!((*x>='A'&&*x<='Z')||(*x>='a'&&*x<='z')))ok=0;size_t k=strlen(comma+1);if(k<1||k>3)ok=0;for(char *x=comma+1;*x;x++)if(*x<'0'||*x>'9')ok=0;}if(!ok){puts("ERROR");continue;}*comma=0;char *end;long v=strtol(comma+1,&end,10);if(*end||v<0||v>999)puts("ERROR");else printf("%s %ld\n",s,v);}return 0;}''',['Potion,12\nBerry,000\n','Potion,12x\nPotion\nA,-1\nA,1000\n','Potion,12','A,1,2\n,1\n A,1\n','A'*100+',1\nB,2\n','Potion,12\r\n'])
lib(21,'Implement swap_levels and heal_in_place returning 1 on success, 0 on invalid input. Null pointers fail. Swap accepts any int and permits identical pointers. For healing: maximum 1..INT_MAX, current 0..maximum, amount 0..INT_MAX, clamping without signed overflow. Driver commands S a b, I a (same address), N (null swap), H current max amount, Z (null healing). Driver prints return value followed by updated values.', '', 'int swap_levels(int *a,int *b);\nint heal_in_place(int *hp,int maximum,int amount);',r'''int swap_levels(int *a,int *b){if(!a||!b)return 0;int t=*a;*a=*b;*b=t;return 1;}int heal_in_place(int *p,int m,int a){if(!p||m<1||*p<0||*p>m||a<0)return 0;*p=a>m-*p?m:*p+a;return 1;}''',r'''int main(void){char c;int a=5,b=10,m,v;if(scanf(" %c",&c)!=1)return 1;if(c=='S'){if(scanf("%d%d",&a,&b)!=2)return 1;int ok=swap_levels(&a,&b);printf("%d %d %d\n",ok,a,b);}else if(c=='I'){if(scanf("%d",&a)!=1)return 1;int ok=swap_levels(&a,&a);printf("%d %d\n",ok,a);}else if(c=='N'){int ok=swap_levels(NULL,&a);printf("%d %d\n",ok,a);}else if(c=='Z')printf("%d\n",heal_in_place(NULL,10,2));else{if(scanf("%d%d%d",&a,&m,&v)!=3)return 1;int ok=heal_in_place(&a,m,v);printf("%d %d\n",ok,a);}return 0;}''',['S 5 10','I 7','N','Z','H 35 39 10','H 1 2147483647 2147483647','H 10 5 1','H 3 5 -1'])
lib(22,'Implement activity_set(Activity*,int tag,int value). Tags: BATTLE=0 (level 1-100), TRAVEL=1 (meters 0-100000), SHOP=2 (cents 0-100000). Return 1 on success; return 0 and preserve the old activity on invalid tag/value or NULL. Set tag and corresponding union field together. Driver reads count followed by tag/value pairs and prints result tag value after each operation; starts at TRAVEL 0.', 'typedef enum {BATTLE,TRAVEL,SHOP} ActivityTag;\ntypedef struct {ActivityTag tag;union {int foeLevel;int distance;int cents;} data;} Activity;', 'int activity_set(Activity *a,int tag,int value);',r'''int activity_set(Activity *a,int t,int v){if(!a||t<0||t>2||v<(t==0?1:0)||v>(t==0?100:100000))return 0;a->tag=(ActivityTag)t;if(t==0)a->data.foeLevel=v;else if(t==1)a->data.distance=v;else a->data.cents=v;return 1;}''',r'''int main(void){Activity a={TRAVEL,{0}};int n;if(scanf("%d",&n)!=1)return 1;for(int i=0;i<n;i++){int t,v;if(scanf("%d%d",&t,&v)!=2)return 1;int ok=activity_set(&a,t,v);int x=a.tag==BATTLE?a.data.foeLevel:a.tag==TRAVEL?a.data.distance:a.data.cents;printf("%d %d %d\n",ok,a.tag,x);}printf("NULL %d\n",activity_set(NULL,0,1));return 0;}''',['3 0 25 1 1500 2 125','4 0 0 3 1 1 -1 2 100001','2 0 100 1 100000'])
main(23,'Input command count 0-100 then commands E index (earn), R index (remove), C index (check). Start with mask 0; valid indices 0-7. Print unsigned mask after E/R, 0 or 1 after C, or ERROR for invalid index/command. Preserve the mask after errors. Use bitwise operations; one output line per command.',r'''int main(void){int n;unsigned int mask=0;if(scanf("%d",&n)!=1||n<0||n>100){puts("ERROR");return 0;}for(int i=0;i<n;i++){char c;int j;if(scanf(" %c%d",&c,&j)!=2)return 1;if(j<0||j>7||(c!='E'&&c!='R'&&c!='C')){puts("ERROR");continue;}unsigned int bit=1u<<j;if(c=='E'){mask|=bit;printf("%u\n",mask);}else if(c=='R'){mask&=~bit;printf("%u\n",mask);}else printf("%u\n",(mask&bit)!=0);}return 0;}''',['4 E 0 E 7 R 0 C 7','5 E 3 E 3 R 2 C 2 C 3','3 E -1 E 8 C 0','2 X 0 C 0'])
main(24,'No stdin. Read battle.txt from the in-app sandbox. Each complete line exactly WIN or LOSS counts accordingly; every other line (including blank) counts as unrecognized. Remove LF or CRLF line endings only. Accept a final line without newline. Print wins losses unrecognized separated by spaces and newline, or ERROR if the file cannot be opened.',r'''int main(void){FILE *f=fopen("battle.txt","r");if(!f){puts("ERROR");return 0;}char s[256];int w=0,l=0,u=0;while(fgets(s,sizeof s,f)){if(!strchr(s,'\n')&&!feof(f)){int c;while((c=fgetc(f))!='\n'&&c!=EOF){}u++;continue;}s[strcspn(s,"\r\n")]=0;if(!strcmp(s,"WIN"))w++;else if(!strcmp(s,"LOSS"))l++;else u++;}fclose(f);printf("%d %d %d\n",w,l,u);return 0;}''',[case('',{'battle.txt':'WIN\nLOSS\nDRAW\n'}),case('',{'battle.txt':''}),case('',{'battle.txt':'WIN\r\nLOSS'}),case(''),case('',{'battle.txt':'WINNER\n\nwin\n'+'W'*300+'\nWIN\n'})])
RECORD='typedef struct {char species[21];int level;} Record;'
lib(10,'Implement save_roster(path,records,count) and load_roster(path,out,count). Return 1 on success, 0 on failure. Capacity 6. Text file: species,level plus newline per record; species is 1-20 ASCII letters, level 1-100. Empty file is valid. Missing file, malformed/trailing data, overlong lines or >6 records fail without changing out or *count. Save rejects invalid records before opening a file. Driver: S n followed by species level records, or L to load roster.txt. It prints success/count and the resulting roster. A failed load keeps the initial Keep,1 record.',RECORD,'int save_roster(const char *path,const Record *items,size_t count);\nint load_roster(const char *path,Record *out,size_t *count);',r'''
static int good_record(const Record *r){size_t n=strlen(r->species);if(n<1||n>20||r->level<1||r->level>100)return 0;for(size_t i=0;i<n;i++)if(!isalpha((unsigned char)r->species[i]))return 0;return 1;}
int save_roster(const char *path,const Record *r,size_t n){if(n>6)return 0;for(size_t i=0;i<n;i++)if(!good_record(r+i))return 0;FILE *f=fopen(path,"w");if(!f)return 0;int ok=1;for(size_t i=0;i<n;i++)if(fprintf(f,"%s,%d\n",r[i].species,r[i].level)<0)ok=0;if(fclose(f))ok=0;return ok;}
int load_roster(const char *path,Record *out,size_t *count){FILE *f=fopen(path,"r");if(!f)return 0;Record tmp[6];size_t n=0;char line[256];int ok=1;while(fgets(line,sizeof line,f)){char tail;Record r;if(n==6||sscanf(line,"%20[A-Za-z],%d %c",r.species,&r.level,&tail)!=2||!good_record(&r)){ok=0;break;}tmp[n++]=r;}if(ferror(f))ok=0;fclose(f);if(!ok)return 0;memcpy(out,tmp,n*sizeof *tmp);*count=n;return 1;}
''',r'''int main(void){Record a[6]={{"Keep",1}};size_t n=1;char cmd;if(scanf(" %c",&cmd)!=1)return 1;if(cmd=='S'){size_t k;Record v[6];if(scanf("%zu",&k)!=1||k>6)return 1;for(size_t i=0;i<k;i++)if(scanf("%20s%d",v[i].species,&v[i].level)!=2)return 1;printf("SAVE %d\n",save_roster("roster.txt",v,k));}int ok=load_roster("roster.txt",a,&n);printf("%d %zu\n",ok,n);if(n>6)return 1;for(size_t i=0;i<n;i++)printf("%s %d\n",a[i].species,a[i].level);return 0;}''',['S 2 Pikachu 12 Zubat 8',case('L',{'roster.txt':'Pikachu,12\nZubat,8\n'}),case('L'),case('L',{'roster.txt':'Pikachu,12x\n'}),case('L',{'roster.txt':''}),case('L',{'roster.txt':'A,1\n'*7}),case('L',{'roster.txt':'A,0\n'})])
NODE='typedef struct {const char *name;int children[3];int count;} Node;'
lib(11,'Implement void print_paths(const Node *nodes,int root). The input is an acyclic tree of at most 16 nodes, with up to three children per node. Print every root-to-leaf path in child order, joining names with > and ending each path with newline. Use recursion. The driver chooses a supplied tree by input 0 (single Eevee), 1 (three Eevee branches), 2 (four-node chain) or 3 (two nested branches).',NODE,'void print_paths(const Node *nodes,int root);',r'''static void walk(const Node *n,int at,int path[16],int depth){path[depth]=at;if(!n[at].count){for(int i=0;i<=depth;i++)printf("%s%s",i?">":"",n[path[i]].name);puts("");return;}for(int i=0;i<n[at].count;i++)walk(n,n[at].children[i],path,depth+1);}void print_paths(const Node *nodes,int root){int path[16];walk(nodes,root,path,0);}''',r'''int main(void){int m;if(scanf("%d",&m)!=1)return 1;Node t[7]={{"Eevee",{1,2,3},3},{"Vaporeon",{0},0},{"Jolteon",{0},0},{"Flareon",{0},0},{"Bud",{0},0},{"Bloom",{0},0},{"Tree",{0},0}};if(m==0)t[0].count=0;if(m==2){t[0].count=1;t[1].count=1;t[1].children[0]=2;t[2].count=1;t[2].children[0]=3;}if(m==3){t[0].name="Seed";t[0].count=2;t[0].children[0]=4;t[0].children[1]=6;t[4].count=1;t[4].children[0]=5;}print_paths(t,0);return 0;}''',['0','1','2','3'])
JOURNAL=OBS+'\ntypedef struct {Observation items[20];size_t count;} Journal;'
lib(12,'Implement the five Journal functions in the starter. Capacity 20; duplicates allowed. Valid species: 1-20 ASCII letters; level 1-100; habitat 0-2. add returns 1/0. find returns count and copies all exact case-sensitive matches in order. Save/load use journal.txt lines species,level,habitat (habitat numeric 0-2). Return 1/0; a failed load preserves the old journal. Driver starts empty: command count then A species level habitat, F species, S, or L. A/S/L print return value. F prints count followed by matching records. All records end with newline.',JOURNAL,'int journal_add(Journal *j,const Observation *r);\nsize_t journal_find(const Journal *j,const char *name,Observation *out);\nint journal_save(const Journal *j,const char *path);\nint journal_load(Journal *j,const char *path);',r'''
static int valid_obs(const Observation *r){size_t n=strlen(r->species);if(!n||n>20||r->level<1||r->level>100||r->habitat<0||r->habitat>2)return 0;for(size_t i=0;i<n;i++)if(!isalpha((unsigned char)r->species[i]))return 0;return 1;}
int journal_add(Journal *j,const Observation *r){if(j->count>=20||!valid_obs(r))return 0;j->items[j->count++]=*r;return 1;}
size_t journal_find(const Journal *j,const char *name,Observation *out){size_t n=0;for(size_t i=0;i<j->count;i++)if(!strcmp(j->items[i].species,name))out[n++]=j->items[i];return n;}
int journal_save(const Journal *j,const char *path){FILE *f=fopen(path,"w");if(!f)return 0;int ok=1;for(size_t i=0;i<j->count;i++)if(fprintf(f,"%s,%d,%d\n",j->items[i].species,j->items[i].level,j->items[i].habitat)<0)ok=0;if(fclose(f))ok=0;return ok;}
int journal_load(Journal *j,const char *path){FILE *f=fopen(path,"r");if(!f)return 0;Journal tmp;memset(&tmp,0,sizeof tmp);char line[256];int ok=1;while(fgets(line,sizeof line,f)){Observation r;int h;char tail;if(sscanf(line,"%20[A-Za-z],%d,%d %c",r.species,&r.level,&h,&tail)!=3){ok=0;break;}r.habitat=(Habitat)h;if(!journal_add(&tmp,&r)){ok=0;break;}}if(ferror(f))ok=0;fclose(f);if(ok)*j=tmp;return ok;}
''',r'''int main(void){Journal j;memset(&j,0,sizeof j);int n;if(scanf("%d",&n)!=1)return 1;for(int i=0;i<n;i++){char c;if(scanf(" %c",&c)!=1)return 1;if(c=='A'){Observation r;int h;if(scanf("%20s%d%d",r.species,&r.level,&h)!=3)return 1;r.habitat=(Habitat)h;printf("%d\n",journal_add(&j,&r));}else if(c=='F'){char s[21];Observation out[20];if(scanf("%20s",s)!=1)return 1;size_t k=journal_find(&j,s,out);if(k>20)return 1;printf("%zu\n",k);for(size_t z=0;z<k;z++)printf("%s %d %d\n",out[z].species,out[z].level,out[z].habitat);}else printf("%d\n",c=='S'?journal_save(&j,"journal.txt"):journal_load(&j,"journal.txt"));}return 0;}''',['5 A Pikachu 12 0 S A Zubat 8 2 L F Zubat','3 A Eevee 5 0 A Eevee 10 1 F Eevee','2 A A 0 0 F A','21 '+' '.join(['A A 5 0']*21),case('3 A Keep 1 0 L F Keep',{'journal.txt':'A,5,3\n'}),case('2 L F Pika',{'journal.txt':'Pika,7,0\n'})])
QUEUE='typedef struct Patient {int id;struct Patient *next;} Patient;\ntypedef struct {Patient *head,*tail;} Queue;'
lib(25,'Implement enqueue, dequeue and queue_destroy using a singly linked list. Queue starts with NULL head/tail. enqueue returns 1 or 0 on allocation failure; any int ID and duplicates are allowed. dequeue writes an ID and returns 1, or returns 0 on empty without changing output. Destroy frees all nodes and sets head/tail NULL. Driver: command count then E id, S (serve), X (destroy), F (fail next allocation). Prints enqueue result, or serve result and ID (initially -999). Ends with CLEAN head-null tail-null and LIVE allocation count. Failure must preserve the queue.',QUEUE,'int enqueue(Queue *q,int id);\nint dequeue(Queue *q,int *id);\nvoid queue_destroy(Queue *q);',r'''int enqueue(Queue *q,int id){Patient *p=malloc(sizeof *p);if(!p)return 0;p->id=id;p->next=NULL;if(q->tail)q->tail->next=p;else q->head=p;q->tail=p;return 1;}int dequeue(Queue *q,int *id){if(!q->head)return 0;Patient *p=q->head;*id=p->id;q->head=p->next;if(!q->head)q->tail=NULL;free(p);return 1;}void queue_destroy(Queue *q){Patient *p=q->head;while(p){Patient *n=p->next;free(p);p=n;}q->head=q->tail=NULL;}''',r'''int main(void){track_ready();Queue q={0};int n;if(scanf("%d",&n)!=1)return 1;for(int i=0;i<n;i++){char c;if(scanf(" %c",&c)!=1)return 1;if(c=='E'){int v;if(scanf("%d",&v)!=1)return 1;printf("%d\n",enqueue(&q,v));}else if(c=='S'){int v=-999;int ok=dequeue(&q,&v);printf("%d %d\n",ok,v);}else if(c=='X')queue_destroy(&q);else fail_next=1;}queue_destroy(&q);printf("CLEAN %d %d\nLIVE %d\n",q.head==NULL,q.tail==NULL,live_blocks());return 0;}''',['7 E 10 E 20 E 30 S S S S','5 E 1 F E 2 S S','5 E 5 X E 7 S S','2 E 4 E 4','0'],True)
INV='typedef struct ItemNode {char name[21];int quantity;struct ItemNode *next;} ItemNode;'
lib(26,'Implement inventory_add, inventory_remove, inventory_find, inventory_destroy for a singly linked list. Names: 1-20 ASCII letters; quantities 0-999. add inserts a new name or adds to its existing quantity, returning 1; invalid data, overflow or allocation failure returns 0 without changes. remove returns 1 if found/freed, else 0. find returns matching node or NULL. destroy sets head NULL. Driver: command count; A name quantity, R name, G name (prints quantity or -1), X destroy, F fail next allocation. Ends with CLEAN head-null and LIVE allocation count.',INV,'int inventory_add(ItemNode **head,const char *name,int quantity);\nint inventory_remove(ItemNode **head,const char *name);\nItemNode *inventory_find(ItemNode *head,const char *name);\nvoid inventory_destroy(ItemNode **head);',r'''ItemNode *inventory_find(ItemNode *h,const char *s){while(h){if(!strcmp(h->name,s))return h;h=h->next;}return NULL;}int inventory_add(ItemNode **h,const char *s,int q){size_t n=strlen(s);if(!n||n>20||q<0||q>999)return 0;for(size_t i=0;i<n;i++)if(!isalpha((unsigned char)s[i]))return 0;ItemNode *p=inventory_find(*h,s);if(p){if(q>999-p->quantity)return 0;p->quantity+=q;return 1;}p=malloc(sizeof *p);if(!p)return 0;strcpy(p->name,s);p->quantity=q;p->next=*h;*h=p;return 1;}int inventory_remove(ItemNode **h,const char *s){while(*h){if(!strcmp((*h)->name,s)){ItemNode *p=*h;*h=p->next;free(p);return 1;}h=&(*h)->next;}return 0;}void inventory_destroy(ItemNode **h){while(*h){ItemNode *p=*h;*h=p->next;free(p);}}''',r'''int main(void){track_ready();ItemNode *h=NULL;int n;if(scanf("%d",&n)!=1)return 1;for(int i=0;i<n;i++){char c,s[21];if(scanf(" %c",&c)!=1)return 1;if(c=='X')inventory_destroy(&h);else if(c=='F')fail_next=1;else{if(scanf("%20s",s)!=1)return 1;if(c=='A'){int v;if(scanf("%d",&v)!=1)return 1;printf("%d\n",inventory_add(&h,s,v));}else if(c=='R')printf("%d\n",inventory_remove(&h,s));else{ItemNode *p=inventory_find(h,s);printf("%d\n",p?p->quantity:-1);}}}inventory_destroy(&h);printf("CLEAN %d\nLIVE %d\n",h==NULL,live_blocks());return 0;}''',['3 A Potion 2 A Potion 3 G Potion','8 A A 1 A B 2 A C 3 R B R C R A G A R Z','5 A A 999 A A 1 G A A B -1 G B','4 A A 2 F A B 2 G A','2 X X'],True)
lib(27,'Implement int find_path(const int maze[5][5],int sr,int sc,int gr,int gc,int path[25][2]). Cells 0=open and 1=wall. Return path length including start and goal, or 0 if unreachable or coordinates invalid. Use recursive DFS, visiting neighbors up, right, down, left in that order; never revisit a cell. Driver input: sr sc gr gc then 25 row-major cells. Prints length, then path coordinates one per line. The input matrix must not be modified.','', 'int find_path(const int maze[5][5],int sr,int sc,int gr,int gc,int path[25][2]);',r'''static int dfs(const int m[5][5],int r,int c,int gr,int gc,int seen[5][5],int path[25][2],int d){if(r<0||r>=5||c<0||c>=5||m[r][c]||seen[r][c])return 0;seen[r][c]=1;path[d][0]=r;path[d][1]=c;if(r==gr&&c==gc)return d+1;const int dr[4]={-1,0,1,0},dc[4]={0,1,0,-1};for(int i=0;i<4;i++){int n=dfs(m,r+dr[i],c+dc[i],gr,gc,seen,path,d+1);if(n)return n;}return 0;}int find_path(const int m[5][5],int sr,int sc,int gr,int gc,int path[25][2]){int seen[5][5]={0};if(gr<0||gr>=5||gc<0||gc>=5)return 0;return dfs(m,sr,sc,gr,gc,seen,path,0);}''',r'''int main(void){int m[5][5],p[25][2],sr,sc,gr,gc;if(scanf("%d%d%d%d",&sr,&sc,&gr,&gc)!=4)return 1;for(int r=0;r<5;r++)for(int c=0;c<5;c++)if(scanf("%d",&m[r][c])!=1)return 1;int n=find_path((const int (*)[5])m,sr,sc,gr,gc,p);if(n<0||n>25)return 1;printf("%d\n",n);for(int i=0;i<n;i++)printf("%d %d\n",p[i][0],p[i][1]);return 0;}''',['0 0 4 4 '+' '.join(map(str,[0,0,1,1,1,1,0,0,0,1,1,0,1,0,1,1,0,1,0,0,1,0,0,0,0])),'0 0 0 0 '+' '.join(['0']*25),'0 0 4 4 '+' '.join(['0']+['1']*24),'0 0 4 4 '+' '.join(['0']*25),'-1 0 4 4 '+' '.join(['0']*25)])
lib(28,'Implement write_record, read_record and record_at. Sandbox ABI: CHAR_BIT=8, unsigned long is 32 bits. Record: species (1-1025) as four little-endian bytes, level (1-100) as two little-endian bytes, no header. Return 1 on success or 0 on invalid data/I/O error. Reads preserve output arguments on failure. record_at validates whole file length is a multiple of six and seeks by 0-based index. Driver input W species level (prints return then written bytes as uppercase hex) or A index (reads archive.bin; prints return species level, initially 7/7). Never write raw structs.','', 'int write_record(FILE *f,unsigned long species,int level);\nint read_record(FILE *f,unsigned long *species,int *level);\nint record_at(FILE *f,size_t index,unsigned long *species,int *level);',r'''int write_record(FILE *f,unsigned long s,int l){if(!f||s<1||s>1025||l<1||l>100)return 0;unsigned char b[6];for(int i=0;i<4;i++)b[i]=(unsigned char)(s>>(8*i));b[4]=(unsigned char)l;b[5]=(unsigned char)((unsigned)l>>8);return fwrite(b,1,6,f)==6;}int read_record(FILE *f,unsigned long *s,int *l){unsigned char b[6];if(!f||!s||!l||fread(b,1,6,f)!=6)return 0;unsigned long n=0;for(int i=0;i<4;i++)n|=(unsigned long)b[i]<<(8*i);int v=b[4]+256*b[5];if(n<1||n>1025||v<1||v>100)return 0;*s=n;*l=v;return 1;}int record_at(FILE *f,size_t i,unsigned long *s,int *l){if(!f||fseek(f,0,SEEK_END))return 0;long size=ftell(f);if(size<0||size%6||i>=(unsigned long)size/6)return 0;if(fseek(f,(long)(i*6),SEEK_SET))return 0;return read_record(f,s,l);}''',r'''int main(void){char c;if(scanf(" %c",&c)!=1)return 1;if(c=='W'){unsigned long s;int l;if(scanf("%lu%d",&s,&l)!=2)return 1;FILE *f=fopen("out.bin","w+b");if(!f)return 1;printf("%d\n",write_record(f,s,l));rewind(f);int b,first=1;while((b=fgetc(f))!=EOF){printf("%s%02X",first?"":" ",b);first=0;}puts("");fclose(f);}else{size_t i;if(scanf("%zu",&i)!=1)return 1;unsigned long s=7;int l=7;FILE *f=fopen("archive.bin","rb");int ok=record_at(f,i,&s,&l);if(f)fclose(f);printf("%d %lu %d\n",ok,s,l);}return 0;}''',['W 25 5','W 1025 100','W 0 5','W 25 101',case('A 1',{'archive.bin':[25,0,0,0,5,0,1,4,0,0,100,0]}),case('A 2',{'archive.bin':[25,0,0,0,5,0]}),case('A 0',{'archive.bin':[25,0,0,0,5]}),case('A 0',{'archive.bin':[0,0,0,0,5,0]}),case('A 0')])
BATTLE='typedef struct {int hp[2][2];int active[2];int potions[2];int turn;int winner;} Battle;'
lib(29,'Implement battle_act(Battle*,char action,int target) returning 1 on valid action, 0 with no state change otherwise. Initial state: both teams have two Pokemon at 40 HP, active indices 0, one potion each, turn 0, winner -1. A attacks for 17 damage; H heals active Pokemon by 20, clamped to 40, consumes one potion (invalid at full HP); S switches to living target index 0 or 1 (invalid if already active). Valid actions consume a turn. A faint automatically selects the first living teammate for free. If both opposing Pokemon faint, set winner to attacker and leave turn there. No actions after a winner. Driver prints result turn winner active0 active1 potions0 potions1 hp00 hp01 hp10 hp11 after each command. Input: count followed by action and target (use 0 for A/H).',BATTLE,'int battle_act(Battle *b,char action,int target);',r'''int battle_act(Battle *b,char a,int target){if(b->winner!=-1)return 0;int t=b->turn,o=1-t,i=b->active[t],j=b->active[o];if(a=='A'){b->hp[o][j]-=17;if(b->hp[o][j]<0)b->hp[o][j]=0;if(!b->hp[o][j]){int other=1-j;if(b->hp[o][other])b->active[o]=other;else{b->winner=t;return 1;}}}else if(a=='H'){if(!b->potions[t]||b->hp[t][i]>=40)return 0;b->potions[t]--;b->hp[t][i]+=20;if(b->hp[t][i]>40)b->hp[t][i]=40;}else if(a=='S'){if(target<0||target>1||target==i||b->hp[t][target]<=0)return 0;b->active[t]=target;}else return 0;b->turn=o;return 1;}''',r'''int main(void){Battle b={{{40,40},{40,40}},{0,0},{1,1},0,-1};int n;if(scanf("%d",&n)!=1)return 1;for(int i=0;i<n;i++){char c;int v;if(scanf(" %c%d",&c,&v)!=2)return 1;int ok=battle_act(&b,c,v);printf("%d %d %d %d %d %d %d %d %d %d %d\n",ok,b.turn,b.winner,b.active[0],b.active[1],b.potions[0],b.potions[1],b.hp[0][0],b.hp[0][1],b.hp[1][0],b.hp[1][1]);}return 0;}''',['1 A 0','5 H 0 S 0 S 2 X 0 A 0','5 A 0 H 0 A 0 H 0 A 0','20 '+' '.join(['A 0']*20),'4 S 1 A 0 S 0 H 0'])
SHOP='typedef struct {char name[21];unsigned stock,price;} StockItem;\ntypedef struct {StockItem *data;size_t count,capacity;unsigned long revenue;} Shop;'
lib(30,'Implement the Shop functions in the starter. init creates empty shop (capacity 2, revenue 0); destroy frees and zeros fields. Capacity doubles up to 20. Names 1-20 ASCII letters, case-sensitive and unique; stock 0-999, price 0-100000 cents. add/restock/sell/save/load return 1 on success, 0 otherwise with no state change. find returns index or -1. Selling checks stock and unsigned-long revenue overflow (32-bit ULONG_MAX=4294967295). Text file shop.txt: first line revenue, then name,stock,price lines. Transactional load rejects malformed/duplicate/over-capacity records. Driver commands: A name stock price; R name count; B name count; G name; S save; L load; F fail next allocation. G prints stock price or MISSING. Other actions print return code; ends with REVENUE value and LIVE count after cleanup. Input begins with command count.',SHOP,'int shop_init(Shop *s);\nvoid shop_destroy(Shop *s);\nint shop_find(const Shop *s,const char *name);\nint shop_add(Shop *s,const char *name,unsigned stock,unsigned price);\nint shop_restock(Shop *s,const char *name,unsigned count);\nint shop_sell(Shop *s,const char *name,unsigned count);\nint shop_save(const Shop *s,const char *path);\nint shop_load(Shop *s,const char *path);',r'''
int shop_init(Shop *s){s->count=s->capacity=0;s->revenue=0;s->data=malloc(2*sizeof *s->data);if(!s->data)return 0;s->capacity=2;return 1;}
void shop_destroy(Shop *s){free(s->data);s->data=NULL;s->count=s->capacity=0;s->revenue=0;}
int shop_find(const Shop *s,const char *n){for(size_t i=0;i<s->count;i++)if(!strcmp(s->data[i].name,n))return (int)i;return -1;}
int shop_add(Shop *s,const char *n,unsigned stock,unsigned price){size_t len=strlen(n);if(!len||len>20||stock>999||price>100000||s->count==20||shop_find(s,n)>=0)return 0;for(size_t i=0;i<len;i++)if(!isalpha((unsigned char)n[i]))return 0;if(s->count==s->capacity){size_t c=s->capacity*2;if(c>20)c=20;StockItem *p=realloc(s->data,c*sizeof *p);if(!p)return 0;s->data=p;s->capacity=c;}StockItem *p=s->data+s->count++;strcpy(p->name,n);p->stock=stock;p->price=price;return 1;}
int shop_restock(Shop *s,const char *n,unsigned count){int i=shop_find(s,n);if(i<0||count>999-s->data[i].stock)return 0;s->data[i].stock+=count;return 1;}
int shop_sell(Shop *s,const char *n,unsigned count){int i=shop_find(s,n);if(i<0||count>s->data[i].stock)return 0;unsigned long price=s->data[i].price;if(price&&count>(ULONG_MAX-s->revenue)/price)return 0;s->data[i].stock-=count;s->revenue+=price*count;return 1;}
int shop_save(const Shop *s,const char *path){FILE *f=fopen(path,"w");if(!f)return 0;int ok=fprintf(f,"%lu\n",s->revenue)>=0;for(size_t i=0;i<s->count;i++)if(fprintf(f,"%s,%u,%u\n",s->data[i].name,s->data[i].stock,s->data[i].price)<0)ok=0;if(fclose(f))ok=0;return ok;}
int shop_load(Shop *s,const char *path){FILE *f=fopen(path,"r");if(!f)return 0;Shop tmp;if(!shop_init(&tmp)){fclose(f);return 0;}char line[256],tail;int ok=fgets(line,sizeof line,f)&&sscanf(line,"%lu %c",&tmp.revenue,&tail)==1;while(ok&&fgets(line,sizeof line,f)){char name[21];unsigned stock,price;if(sscanf(line,"%20[A-Za-z],%u,%u %c",name,&stock,&price,&tail)!=3||!shop_add(&tmp,name,stock,price))ok=0;}if(ferror(f))ok=0;fclose(f);if(!ok){shop_destroy(&tmp);return 0;}shop_destroy(s);*s=tmp;return 1;}
''',r'''int main(void){track_ready();Shop s={0};if(!shop_init(&s))return 1;int n;if(scanf("%d",&n)!=1)return 1;for(int i=0;i<n;i++){char c,name[21];unsigned a,b;if(scanf(" %c",&c)!=1)return 1;if(c=='F'){fail_next=1;continue;}if(c=='S'||c=='L'){printf("%d\n",c=='S'?shop_save(&s,"shop.txt"):shop_load(&s,"shop.txt"));continue;}if(scanf("%20s",name)!=1)return 1;if(c=='G'){int k=shop_find(&s,name);if(k<0)puts("MISSING");else printf("%u %u\n",s.data[k].stock,s.data[k].price);continue;}if(scanf("%u",&a)!=1)return 1;if(c=='A'){if(scanf("%u",&b)!=1)return 1;printf("%d\n",shop_add(&s,name,a,b));}else printf("%d\n",c=='R'?shop_restock(&s,name,a):shop_sell(&s,name,a));}printf("REVENUE %lu\n",s.revenue);shop_destroy(&s);printf("LIVE %d\n",live_blocks());return 0;}''',['5 A Potion 3 200 B Potion 2 G Potion B Potion 2 G Potion','6 A A 999 100 A A 1 2 R A 1 B Missing 1 S L','6 A A 1 2 A B 1 3 F A C 1 4 G A G C',case('4 L G A B A 1 G A',{'shop.txt':'4294967295\nA,2,1\n'}),case('3 A Keep 2 3 L G Keep',{'shop.txt':'0\nBad,5,1\nBad,2,1\n'}),case('3 A Keep 2 3 L G Keep',{'shop.txt':'oops\n'}),'4 A A 2 3 S B A 1 L'],True)
assert set(D)==set(range(1,31)),set(range(1,31))-set(D)
for q in qs:
 n=int(q['id'][-2:]);d=D[n]
 q.update(schemaVersion=4,contentStatus='autograded',implementationContract=d['contract'],prompt=d['contract'],starterCode=d['starter'],inputPolicy='Exact output is required: case, spaces, numbers and final newlines must match. No extra prompts or labels. Every test starts in a fresh sandbox. C11 compilation uses -Wall -Wextra -Werror -pedantic-errors. Standard library files are in-memory only. Run uses the test driver for function labs. Submit must pass every test. Runtime limits: 3 seconds per test, 64 MB program memory, 16 KB output. Compiler preparation may take longer.',learningObjectives=[d['contract']])
 q['validation']={'mode':'autograder','publicationReady':True}
 q['rewardPolicy']['grantOn']='autograded-completion'
 q['grading']={'version':1,'mode':'functions' if d['harness'] else 'program','harness':d['harness'],'tests':[dict(id=q['id']+'-case-'+str(i+1),label='Case '+str(i+1),**t) for i,t in enumerate(d['cases'])]}
 for k in ['fixture','testAdvice','example','acceptance','deliverables','rubric','hintsPolicy','optionalExtension']:q.pop(k,None)
 q['hints']=[q['hints'][0],'Implement the exact contract above. For function labs, keep the starter types and signatures; the game supplies main().','Use Run with the sample input, then test boundaries. Submit compares every output byte; extra spaces or missing newlines fail.']
(ROOT/'js/data/side-quests.js').write_text('// Thirty C11 labs with exact executable autograder contracts.\nwindow.SIDE_QUESTS = '+json.dumps(qs,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
(ROOT/'tools/quest-reference-fixtures.json').write_text(json.dumps({f'c-lab-{n:02}':d['reference'] for n,d in D.items()},indent=2),encoding='utf-8')
print('Built 30 strict contracts with '+str(sum(len(d['cases']) for d in D.values()))+' executable cases.')
# Re-injecting verified expected outputs is part of building, not a separate step
# somebody has to remember. Expectations whose contract changed are dropped by
# the apply step, so a rebuilt lab is ungradeable until it is re-verified with
# tools/build-expected-outputs.cjs rather than graded against a stale answer.
import subprocess
print(subprocess.run(['node','tools/apply-expected-outputs.cjs'],cwd=str(ROOT),capture_output=True,text=True).stdout.strip())
