// Turns tools/raw-pokeapi.json into js/data/pokedex.js (a plain <script> file, no modules,
// so index.html works by double-clicking it from the filesystem).
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const raw = JSON.parse(await fs.readFile(path.join(ROOT, 'tools', 'raw-pokeapi.json'), 'utf8'));

const byName = {};
for (const m of raw.mons) byName[m.name] = m;

// ---- pick 4 moves per Pokemon, spread across the four question tiers -------------------
// A move's power decides which difficulty of C question you must answer to land it.
function tierOf(power) {
  if (power <= 45) return 1;
  if (power <= 70) return 2;
  if (power <= 95) return 3;
  return 4;
}
const moveEntries = Object.entries(raw.moves).sort(([a], [b]) => a.localeCompare(b));

function pickMoves(mon) {
  const known = new Set(mon.learnset);
  const cands = moveEntries.filter(([n]) => known.has(n));
  const chosen = [];
  const used = new Set();
  for (const tier of [1, 2, 3, 4]) {
    // prefer same-type-attack-bonus moves the mon can actually learn
    const inTier = cands.filter(([n, m]) => tierOf(m.power) === tier && !used.has(n));
    const stab = inTier.filter(([, m]) => mon.types.includes(m.type));
    const bag = stab.length ? stab : inTier;
    if (bag.length) {
      const pickIdx = (mon.id * 7 + tier * 13) % bag.length; // deterministic, varied
      const [n, m] = bag[pickIdx];
      used.add(n);
      chosen.push({ id: n, label: m.label, type: m.type, power: m.power, acc: m.acc, pp: m.pp, tier });
    }
  }
  // fill any missing tier with a generic move so every mon always has 4 buttons
  const FALLBACK = { 1: 'tackle', 2: 'body-slam', 3: 'slash', 4: 'hyper-beam' };
  for (const tier of [1, 2, 3, 4]) {
    if (!chosen.some(c => c.tier === tier)) {
      const n = FALLBACK[tier];
      const m = raw.moves[n];
      if (m) chosen.push({ id: n, label: m.label, type: m.type, power: m.power, acc: m.acc, pp: m.pp, tier });
    }
  }
  chosen.sort((a, b) => a.tier - b.tier);
  return chosen;
}

const dex = raw.mons.map(m => ({
  id: m.id,
  name: m.name,
  types: m.types,
  bst: m.stats.hp + m.stats.attack + m.stats.defense + m.stats['special-attack'] + m.stats['special-defense'] + m.stats.speed,
  stats: {
    hp: m.stats.hp, atk: m.stats.attack, def: m.stats.defense,
    spa: m.stats['special-attack'], spd: m.stats['special-defense'], spe: m.stats.speed
  },
  height: m.height, weight: m.weight,
  genus: m.genus, flavor: m.flavor,
  rate: m.capture_rate,
  legendary: m.legendary,
  cry: m.hasCry,
  moves: pickMoves(m),
  evo: (raw.evo[m.name] || []).map(e => ({
    to: byName[e.to] ? byName[e.to].id : null,
    level: e.level || (e.trigger === 'level-up' ? 30 : 32),
    how: e.trigger === 'use-item' ? (e.item || 'stone') : e.trigger
  })).filter(e => e.to)
}));

const out =
  '/* Generated by tools/build-data.mjs from PokeAPI. Do not hand-edit. */\n' +
  'window.DEX = ' + JSON.stringify(dex) + ';\n' +
  'window.TYPE_CHART = ' + JSON.stringify(raw.chart) + ';\n';

await fs.writeFile(path.join(ROOT, 'js', 'data', 'pokedex.js'), out);
console.log('wrote js/data/pokedex.js  (' + dex.length + ' species, ' +
  (out.length / 1024).toFixed(0) + ' KB)');

// sanity: every mon has 4 moves
const bad = dex.filter(d => d.moves.length !== 4);
console.log(bad.length ? 'WARN mons without 4 moves: ' + bad.map(b => b.name).join(',') : 'all species have 4 moves');
