const fs=require('fs'),r='C:/Users/minal/Cmon/';
function edit(file,fn){let p=r+file;fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n')));}
edit('index.html',s=>s.replace('<script src="js/engine/state.js">','<script src="js/data/trainers.js"></script>\n<script src="js/engine/state.js">').replace('<script src="js/main.js">','<script src="js/engine/friends.js"></script>\n<script src="js/main.js">').replace('<section id="s-stats"','<section id="s-friends" class="screen"></section>\n  <section id="s-stats"').replace('</nav>','  <button data-scr="friends" onclick="openFriends()">♥ Friends</button>\n</nav>').replace('<link rel="stylesheet" href="css/parchment.css">','<link rel="stylesheet" href="css/parchment.css">\n<link rel="stylesheet" href="css/friends.css">'));
edit('js/engine/state.js',s=>s.replace('    v: 1,','    v: 1,\n    friends: {},\n    friendScene: null,').replace('    return true;\n  } catch','    ensureFriends();\n    return true;\n  } catch').replace('      S = o; saveGame(); done(null);','      S = o;\n      var defaults=freshSave();\n      for(var key in defaults) if(!(key in S)) S[key]=defaults[key];\n      S.settings=Object.assign({},defaults.settings,S.settings);\n      ensureFriends(); saveGame(); done(null);'));
edit('js/engine/battle.js',s=>{
s=s.replace('    kind: cfg.kind,','    kind: cfg.kind,\n    friendId: cfg.friendId || null,\n    friendEligible: !!cfg.friendEligible,\n    friendRewarded: false,');
s=s.replace('function winBattle() {\n  B.over = true;','function winBattle() {\n  if (!B || B.over) return;\n  if (B.kind === \'trainer\') { finishFriendBattle(true); return; }\n  B.over = true;');
s=s.replace('function loseBattle() {\n  B.over = true;','function loseBattle() {\n  if (!B || B.over) return;\n  if (B.kind === \'trainer\') { finishFriendBattle(false); return; }\n  B.over = true;');
s=s.replace('  saveGame();\n  showResult(true,', '  syncFriendStory();\n  saveGame();\n  showResult(true,');
// Delay callbacks belong to one battle. Leaving or starting another invalidates them.
s=s.replaceAll('setTimeout(', 'battleLater(');
s=s.replace("  battleLater(function () { showScreen('map'); renderMap(); }, 700);", "  showScreen('map'); renderMap();");
s='function battleLater(fn, ms) { var owner=B; return setTimeout(function(){if(B===owner && owner && !owner.over) fn();},ms); }\n'+s;
s=s.replace('  B.q = got.q;', '  B.qAnswered = false;\n  B.q = got.q;');
s=s.replace('  if (!B.q || B.over) return;','  if (!B.q || B.over || B.qAnswered) return;\n  B.qAnswered = true;');
return s;});
edit('js/engine/ui.js',s=>s.replace('function showScreen(name) {\n  CUR = name;',"function showScreen(name) {\n  if (CUR === 'battle' && name !== 'battle' && B && !B.over) {\n    B.over=true; clearInterval(B.timer); saveGame();\n  }\n  CUR = name;").replace('function modal(html) {', 'function modal(html) {').replace("  var h = '<h2>The C-Region</h2>' +", "  var h = '<h2>The C-Region</h2>' +").replace("  h += '</div>';\n  $('#s-map').innerHTML = h;", "  h += '</div><div class=\"panel town-invite\"><h3>Take a break in town</h3><p>Rowan and the others are around. Stop for a chat, make plans, or try a practice match.</p><button onclick=\"openFriends()\">Visit your friends</button></div>';\n  $('#s-map').innerHTML = h;"));
edit('js/main.js',s=>s.replace("    if (e.key === 'Enter' || e.key === 'Escape') {\n      var b = $('#modal .box button.primary') || $('#modal .box button');\n      if (b) b.click();\n    }", "    if (e.key === 'Escape') { e.preventDefault(); closeModal(); }\n    // Enter uses the focused control, so it never chooses a different reply.").replace("  var prefix = CUR === 'drill'", "  if (CUR !== 'battle' && CUR !== 'drill') return;\n  var prefix = CUR === 'drill'"));
// Specific copy edits first, then remove em dashes from all displayed local text.
edit('js/engine/ui.js',s=>s.replace('A little courage.<br>A lifelong companion.','Choose your first partner.').replace('Pick the partner you want beside you as you master C.','Pick your favorite. You can catch the others later.').replace('All fifteen badges. The gauntlet is open — this is the exam simulator.','You have all fifteen badges. These battles draw questions from several chapters.').replace('Every route is open — go wherever you are studying tonight.','Every route is open. Pick the chapter you want to practice.').replace('No battle, no timer — just the material.','Take your time. There is no battle or timer here.').replace('Nothing missed. Go and sit the real one.','You got every question right. Try another paper or review a different chapter.').replace('Poké Center — heal everyone','Poké Center: heal everyone'));
edit('js/engine/battle.js',s=>s.replace('The air goes still... a wild ','A rare visitor! ').replace('It capitalised on your mistake!','Your guard was down!').replace('Answer correctly and the ball gets a real shake. Catch chance if correct: ','A correct answer improves your catch chance to ').replace('The ball wobbled weakly and broke - you have to know the material.','The Pokémon broke free. We will practice that question again.').replace('You are the CHAMPION. Fifteen chapters, conquered.','You are the Champion! You have cleared every gym and the final challenge.').replace('You scrambled back to the Poké Center. Everyone was healed.','You returned to the Poké Center. Your team is fully healed.'));
edit('index.html',s=>s.replace('Small steps. Stronger partners.','Study a little. Stay for a battle.').replace('Every attack costs you a C question —','Answer a C question to attack.').replace('and the stronger the move, the harder the question.','Stronger moves ask harder questions.').replace('Everything you get wrong comes back on a spaced-repetition schedule, and the Trainer Card','Missed questions come back for review. Your Trainer Card').replace('tells you exactly which chapters to study. All sprites, cries and stats are real data','shows which chapters need more practice. Pokémon sprites, cries and stats come').replace('from PokéAPI, stored locally — it works with no internet.','from PokéAPI. They are saved on your computer, so you can play offline.'));
function sweep(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=dir+'/'+e.name;if(e.isDirectory())sweep(p);else if(/\.(js|html)$/.test(e.name)){let s=fs.readFileSync(p,'utf8');if(s.includes('—'))fs.writeFileSync(p,s.replace(/\s*—\s*/g,', '));}}}sweep(r+'js');edit('index.html',s=>s.replace(/\s*—\s*/g,', '));
// Simple original trainer portraits, stored locally as SVG illustrations.
fs.mkdirSync(r+'assets/trainers',{recursive:true});
const people=[['rowan','#ad644b','#56372c','#d9a878','M29 75L28 44 48 23 75 18 98 35 94 72 80 45 69 59 56 45 38 77Z'],['mira','#78895b','#643b26','#e8b58d','M26 92V53Q23 16 61 18Q103 14 99 64L108 111 84 111 83 50Q64 74 37 51L41 108 22 108Z'],['theo','#638699','#303631','#bc8965','M27 69L25 38Q63 2 99 38L99 72 84 50 40 52Z'],['june','#ba8752','#804628','#e3aa7c','M26 88L24 52Q29 12 67 17Q102 19 98 64L113 103 90 113 82 53 37 61 42 98Z'],['ellis','#95788b','#49362f','#d8aa8a','M25 88L23 43Q40 13 75 20L102 44 97 89 82 72 83 47 57 62 38 51 40 90Z']];
for(const [id,coat,hair,skin,shape] of people){fs.writeFileSync(r+'assets/trainers/'+id+'.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 156"><rect width="128" height="156" rx="10" fill="#eddbb7"/><circle cx="65" cy="72" r="51" fill="#f9edcf"/><path d="M14 156V131Q17 105 50 102H80Q112 107 116 136V156" fill="${coat}" stroke="#593e2d" stroke-width="3"/><path d="M53 88v23l11 12 13-12V88" fill="${skin}" stroke="#593e2d" stroke-width="3"/><path d="${shape}" fill="${hair}" stroke="#593e2d" stroke-width="3"/><ellipse cx="64" cy="68" rx="29" ry="37" fill="${skin}" stroke="#593e2d" stroke-width="3"/><path d="M34 57Q31 24 65 25Q96 24 95 55L82 43 66 52 48 43Z" fill="${hair}"/><path d="M47 68h5m25 0h5" stroke="#3e2e24" stroke-width="4" stroke-linecap="round"/><path d="M58 85q7 6 14-1" fill="none" stroke="#70452f" stroke-width="2.5" stroke-linecap="round"/><path d="M42 108l22 20 21-20M64 128v27" fill="none" stroke="#f8e8c7" stroke-width="4"/>${id==='theo'?'<g fill="none" stroke="#493a30" stroke-width="3"><rect x="38" y="59" width="23" height="19" rx="4"/><rect x="69" y="59" width="23" height="19" rx="4"/><path d="M61 65h8"/></g>':''}${id==='june'?'<path d="M18 39h89L91 25H42Z" fill="#bc9561" stroke="#63482e" stroke-width="3"/>':''}${id==='ellis'?'<path d="M26 35Q32 9 72 15L95 31 80 40Z" fill="#6d5b79" stroke="#513947" stroke-width="3"/>':''}${id==='mira'?'<path d="M87 45q-12-15 4-18q14 6-1 20" fill="#e4b578" stroke="#87683d" stroke-width="2"/>':''}</svg>`);}
