"""Measure where the creature actually sits inside each sprite frame.

PokeAPI sprites are fixed frames with the creature floating somewhere inside.
The battle scene needs to put its feet on a platform, so it needs to know how
much transparent space is below it and how far off-centre it is. Measuring this
at build time means the game does not have to read pixels back from a canvas,
which a page opened straight off the disk (file://) is not allowed to do.

Writes js/data/sprite-seat.js.  Run after tools/build-data.mjs.
"""
import json, os, glob
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = 25
out = {}

for kind in ('front', 'back', 'shiny'):
    d = os.path.join(ROOT, 'assets', 'sprites', kind)
    for path in glob.glob(os.path.join(d, '*.png')):
        sid = os.path.splitext(os.path.basename(path))[0]
        try:
            im = Image.open(path).convert('RGBA')
        except Exception:
            continue
        w, h = im.size
        alpha = im.getchannel('A')
        bbox = alpha.point(lambda v: 255 if v > A else 0).getbbox()
        if not bbox:
            continue
        x0, y0, x1, y1 = bbox                      # x1/y1 exclusive
        bottom = round((h - y1) / h, 4)            # transparent fraction below
        cx = round(((x0 + x1) / 2) / w, 4)         # horizontal centre of the art
        out.setdefault(kind, {})[sid] = [bottom, cx]

js = ('/* Generated by tools/measure-sprites.py. Do not hand-edit.\n'
      '   id -> [transparent fraction below the creature, its horizontal centre]. */\n'
      'window.SPRITE_SEAT_DATA = ' + json.dumps(out, separators=(',', ':')) + ';\n')
dest = os.path.join(ROOT, 'js', 'data', 'sprite-seat.js')
open(dest, 'w', encoding='utf-8').write(js)
print('wrote js/data/sprite-seat.js  (%.0f KB)' % (len(js) / 1024))
for k, v in out.items():
    print('  %-6s %d sprites' % (k, len(v)))
